Farfetch/maestro

- .github/workflows/release-beta.yml
- .github/workflows/release.yml
> feat: add agent image release to docker registry

- site/docusaurus.config.js
Fixing a link for editing documentation pages.
> fix: edit documentation edit link

- README.md
> feat: add status badges from shields.io

- web/frontend/src/pages/RunSingle.js
> fix: use run status property for page auto-reload 

- web/api/maestro_api/api_routes.py
- web/api/maestro_api/controllers/run_plan.py
- web/api/maestro_api/libs/jmx.py
- web/api/maestro_api/libs/utils.py
- web/api/maestro_api/settings.py
- web/api/maestro_api/swagger/template.yml
- web/api/maestro_api/validation_schemas.py
- web/api/tests/libs/test_jmx.py
> feat: add `maestroBackendListener` plugin to JMeter test plan

- agent/maestro_agent/services/jmeter/properties.py
- agent/maestro_agent/services/maestro_api/run_plan.py
- agent/tests/services/jmeter/test_properties.py
> feat: download modified JMeter test plan with `maestroBackListener`enabled

- web/api/maestro_api/api_routes.py
- web/api/maestro_api/controllers/run.py
- web/api/maestro_api/libs/utils.py
- web/api/maestro_api/swagger/template.yml
- web/api/maestro_api/validation_schemas.py
- web/api/tests/routes/test_run.py
> feat: add filter params to GET `/runs` endpoint

- web/api/maestro_api/controllers/run_configuration.py
- web/api/maestro_api/db/models/run_configuration.py
- web/api/maestro_api/enums.py
- web/api/maestro_api/swagger/template.yml
- web/api/maestro_api/validation_schemas.py
- web/api/tests/routes/test_run_configuration.py
> feat: add schedule for `RunConfiguration` model

- web/frontend/src/components/RunConfiguration/Form/RunConfigurationForm.js
- web/frontend/src/lib/date.js
- web/frontend/src/pages/TestsSingle.js
> fix: schedule time storing format

- web/api/maestro_api/__init__.py
- web/api/maestro_api/controllers/run.py
- web/api/maestro_api/db/models/run_configuration.py
- web/api/maestro_api/db/repo/run.py
- web/api/maestro_api/scheduler.py
- web/api/maestro_api/settings.py
- web/api/scheduler.py
- web/api/tests/test_scheduler.py
> feat: start run by using schedule from configuration

- web/api/maestro_api/auth_routes.py
- web/api/maestro_api/db/models/user.py
- web/api/maestro_api/db/models/workspace.py
- web/api/maestro_api/db/repo/user.py
- web/api/maestro_api/services/auth/authorization.py
- web/api/maestro_api/services/auth/oauth.py
- web/api/maestro_api/services/auth/request_validator.py
- web/api/maestro_api/settings.py
- web/api/tests/db/repo/test_user.py
- web/api/tests/services/auth/test_oauth.py
> feat: create user and workspace during sing in

- web/api/maestro_api/api_routes.py
- web/api/maestro_api/controllers/user.py
- web/api/maestro_api/controllers/workspace.py
- web/api/maestro_api/db/models/user.py
- web/api/maestro_api/db/repo/user.py
- web/api/maestro_api/swagger/template.yml
- web/api/maestro_api/validation_schemas.py
- web/api/tests/db/repo/test_repo_user.py
- web/api/tests/routes/test_user.py
- web/api/tests/routes/test_workspace.py
Related to: https://github.com/Farfetch/maestro/issues/277
> feat: GET, PUT, POST for users and workspaces

- web/api/maestro_api/__init__.py
- web/api/maestro_api/monitoring.py
> feat: add GET `/monitoring` endpoints

- web/api/maestro_api/api_routes.py
- web/api/maestro_api/controllers/user.py
- web/api/maestro_api/controllers/workspace.py
- web/api/maestro_api/swagger/template.yml
- web/api/tests/routes/test_user.py
- web/api/tests/routes/test_workspace.py
Related https://github.com/Farfetch/maestro/issues/277
> feat: DELETE `/user/id>`, `/workspace/<id>` endpoints

- web/api/maestro_api/controllers/user.py
- web/api/tests/routes/test_user.py
Related: #277 
Adding a validator to return proper error message when user is trying to be created or update with already existed email
> fix: add unique email user validation

- .github/workflows/ci.yml
- agent/Dockerfile
- web/Dockerfile
> deps: upgrade pip to 22.0.4 and pipenv to 2022.3.23

- web/api/maestro_api/controllers/run_configuration.py
- web/api/tests/routes/test_run_configuration.py
Fixing an issue when we delete run configuration without runs
> fix: delete runs along with run confiuguration

- cli/.vscode/settings.json
- cli/cli.py
- cli/maestro_cli/commands/run.py
- cli/maestro_cli/services/maestro_api/__init__.py
- cli/maestro_cli/services/maestro_api/run.py
- cli/maestro_cli/services/maestro_api/run_metric.py
- cli/tests/services/maestro_api/test_run.py
- cli/tests/services/maestro_api/test_run_metric.py
Closes https://github.com/Farfetch/maestro/issues/308
> feat: create and start Run from command line

- web/api/maestro_api/swagger/template.yml
Fixing an issue with wrong description of response time
> fix: create Run response shema

- web/api/maestro_api/auth_routes.py
- web/api/maestro_api/settings.py
Enabling possibility to pass username and password for MongoDB
> feat: add MONGODB auth environment variables

- web/api/maestro_api/auth_routes.py
- web/api/maestro_api/db/repo/user.py
- web/api/maestro_api/templates/login.html
- web/api/tests/db/repo/test_repo_user.py
Admin users have an issue with logins because role override. 
The fix should solve the issue and respect user manual role updates from UI.
> fix: role override during login

- web/api/maestro_api/settings.py
- web/api/wsgi.py
Adding env variable to be able to enable scheduler as part of main API process.
> feat: ability to enable scheduler with api

- web/api/maestro_api/scheduler.py
Fixes an issue when the test is not picked up by the agent when the scheduler is used.
> fix: generate event to notify agents to start a test

- web/frontend/src/components/Run/RunningStatus/AnalyticCharts/RunAnalyticCharts.js
Changing the time interval from 1s to 5s.
> feat: Change time interval default value

- web/frontend/package.json
- web/frontend/yarn.lock
> Revert "build(deps): bump react-chartjs-2 from 3.3.0 to 4.3.1 in /web/frontend"

- web/api/Pipfile.lock
Fixing Pipifile.lock after dependencies update
> fix: regenerate pipfile.lock

- jmeter/Dockerfile
> feat: updates JMeter version to 5.5

- web/frontend/src/components/Run/RunningStatus/AnalyticCharts/RunAnalyticCharts.js
- web/frontend/src/components/Run/RunningStatus/EndpointCharts/HitsErrorsLabelLine/HitsErrorsLabelLine.js
- web/frontend/src/components/Run/RunningStatus/EndpointCharts/RunEndpointCharts.js
- web/frontend/src/components/Run/RunningStatus/RunRunningStatus.js
Adding the option to select, and deselect all endpoints
> feat: add select/deselect endpoints

- web/frontend/src/components/Run/RunningStatus/RunRunningStatus.js
Adding more information about when run started.
> feat: add time when run started

- web/frontend/src/components/RunConfiguration/Form/RunConfigurationForm.js
Add a button to be able to clone and Run Configuration
> feat: add clone button to run configuration

- .gitignore
- web/frontend/.gitignore
- web/frontend/src/components/Dashboard/Card/DashboardCard.js
Fixes negative error percentage showing in Dashboard while test is running 
Adds .vscode and .env to .gitignore in Maestro and frontend respectively
Closes #670
> feat: fix negative percentage error

- web/frontend/src/components/Dashboard/Card/DashboardCard.js
- web/frontend/src/components/Run/RunningStatus/SummaryTable/RunSummaryTable.js
Fixes decimal value shown in error rate, now the value is displayed between 0 and 100% instead of just 0 and 1%
Closes #683
> feat: fix incorrect decimal value in error rate

- agent/maestro_agent/app_state.py
- agent/maestro_agent/logging.py
- agent/maestro_agent/services/logging/handlers.py
Change the log handler from _MaestroApiHandler(StreamHandler)_ to _QueueHandler_ 
None
> Feat: Change log handler to QueueHandler

- web/frontend/src/components/Dashboard/RunsMonitor/RunsMonitor.js
- web/frontend/src/context/Running/RunningContext.js
The logic present in RunsMonitor.js was being duplicated in RunningContext.js, so the code was refactored so that RunsMonitor.js now simply accesses the variables values in RunningContenxt.js
Closes #697
> feat: RunsMonitor logic was added to RunningContext

- web/frontend/package.json
- web/frontend/src/ErrorHandler.js
- web/frontend/src/components/CustomErrorMessage/CustomErrorMessage.js
- web/frontend/src/components/CustomErrorMessage/custom.css
- web/frontend/src/components/CustomErrorMessage/index.js
- web/frontend/src/index.js
- web/frontend/src/lib/api/endpoints/agent.js
- web/frontend/src/lib/api/endpoints/agentLog.js
- web/frontend/src/lib/api/endpoints/customData.js
- web/frontend/src/lib/api/endpoints/run.js
- web/frontend/src/lib/api/endpoints/runAgent.js
- web/frontend/src/lib/api/endpoints/runConfiguration.js
- web/frontend/src/lib/api/endpoints/runMetric.js
- web/frontend/src/lib/api/endpoints/runPlan.js
- web/frontend/src/lib/api/endpoints/user.js
- web/frontend/src/lib/api/endpoints/workspace.js
- web/frontend/src/pages/Agents.js
- web/frontend/src/pages/Layout/layout.css
- web/frontend/yarn.lock
The application now handles errors. It was created a class named _ErrorHandler_ that treats all errors that might occur when interacting with the API. If an error is caught, a pop up message will show up stating which error occurred and can be dismissed by clicking it. Also, it was added an _ErrorBoundary_ from react that encapsulates all the application and catches errors that might cause the application to not render its components.
Closes #686
> Feat: Adds modal for error handling using axios lib and ErrorBoundary
