Farfetch/maestro

web/api/maestro_api/controllers/run.py, web/api/maestro_api/db/models/run.py, web/api/maestro_api/swagger/template.yml, web/api/maestro_api/validation_schemas.py, web/api/tests/routes/test_run.py
Part of #108 
Adding notes field to update and also to be able to fetch along with All Run data. For now, the field created is empty during run creation and there is no way to add a default value.
=> feat: update PUT `/run/{id}` with notes field

.github/workflows/deploy.yml, site/docusaurus.config.js, site/src/pages/index.js
Closes #168 
Maestro site would be available at [farfetch.github.io/maestro](https://farfetch.github.io/maestro) and deployed once anything changed in the `site` or `docs` folder.
=> feat: init GitHub pages deployment

README.md
Updating links to open the website directly instead of Readme files to make navigation more reach.
=> chore: update usage documentation links

agent/maestro_agent/services/running_test/threads_manager.py, agent/maestro_agent/settings.py
Adds metric collector toggle to enable CSV Writer mode or Backend Listener mode.
Refs #54 
=> feat: add `MAESTRO_CSV_WRITER_ENABLED` toggle

web/api/maestro_api/controllers/run.py, web/api/maestro_api/controllers/run_configuration.py, web/api/maestro_api/db/models/run.py, web/api/maestro_api/db/models/run_configuration.py, web/api/maestro_api/swagger/template.yml, web/api/maestro_api/validation_schemas.py, web/api/tests/routes/test_run.py, web/api/tests/routes/test_run_configuration.py
Adding labels as part of each Run, RunConfiguration object. They would be used in the frontend to add/update to categorize tests. 
Related to #109
=> feat: add labels field for `Run`, `RunConfiguration` objects

web/frontend/src/components/Run/RunningStatus/RunRunningStatus.js
There was an issue when we were showing the timer. Adding a condition to not show timer when there is no metric available since we have another one.
=> fix: conditions when to show running test timer

web/frontend/src/components/Run/RunningStatus/MoreButtonsMenu/MoreButtonsMenu.js, web/frontend/src/components/Run/RunningStatus/MoreButtonsMenu/MoreButtonsMenu.test.js, web/frontend/src/components/Run/RunningStatus/MoreButtonsMenu/__snapshots__/MoreButtonsMenu.test.js.snap, web/frontend/src/components/Run/RunningStatus/MoreButtonsMenu/index.js, web/frontend/src/components/Run/RunningStatus/RunRunningStatus.js, web/frontend/src/lib/routes.js
Closes #234 
The button to download logs would be available only when the test is stopped or finished. 
Eventually, after clicking on the button Maestro will open a new tab and download the ZIP archive with all logs from the agent.
Based on #278
=> feat: add button to download logs

docker-compose.yml
Simplifying configuration of docker-compose to use images that are already built. 
We might also improve this part by adding an environment variable with the version, but I believe it's okay to just have this as an example.
Another idea, is would be also good to have `latest`, `beta` docker images that could be used in docker compose
=> feat: use images from docker registry

web/api/maestro_api/db/repo/run_metric.py, web/api/tests/routes/test_run_metric.py
Fixing the time interval when show_labels is empty and the time interval is zero
Closes #304
=> fix: metrics response with time interval 0

web/api/maestro_api/controllers/run_metric.py
Disabling the cache on the metrics results once it was caching on memory a big number of data.
=> feat:  Disable cache on the metrics results

web/frontend/src/components/Run/RunningStatus/SummaryTable/RunSummaryTable.js
Part of https://github.com/Farfetch/maestro/issues/183
Adding metrics about messages and response codes for a specific label
=> feat: add expandable view over label

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/release-beta.yml, .github/workflows/release.yml
GitHub updated the ubuntu latest version to 22.04 which doesn't have the 3.9.5 python version. That is causing the pipeline to fail.
We're setting a specific Ubuntu version to 20.04 to overcome the issue.
=> fix: specify ubuntu version for github actions

web/api/maestro_api/controllers/run_plan.py
Fix the name of a JMX file when downloaded. The filename no longer is the GUID, now is the same of the original JMX file.
Closes #380
=> feat: change name of jmx file download

web/frontend/.eslintrc.js, web/frontend/src/components/Run/RunningStatus/SummaryTable/RunSummaryTable.js
- Adds Latency P99% and Error Count metrics to the Run Summary Table
- Fixes the total Error Rate value displayed
- Changes the order of the old layout
Current Layout:
Closes #183
=> feat: add new metrics on the summary page

web/api/maestro_api/db/models/run.py, web/api/maestro_api/libs/datetime.py, web/api/maestro_api/services/jmeter.py, web/api/tests/libs/test_datetime.py, web/api/tests/routes/test_run.py
When starting a test, no longer displays 01:00:00. Now the test starts at 00:00:00 and everything is timed correctly
Adds a new method to maintain time format coherence expected in tests
Corrects a typo in some functions name on test file
Closes #687
=> fix: +1 hour error when running test, added method keep time format, correct typo in test functions

web/api/maestro_api/controllers/run_configuration.py, web/api/maestro_api/db/models/run_configuration.py, web/api/maestro_api/validation_schemas.py, web/frontend/src/components/RunConfiguration/Form/FormItems/LoadConfiguration/LoadConfigurationFormItem.js, web/frontend/src/components/RunConfiguration/Form/FormItems/LoadConfiguration/LoadConfigurationFormItem.test.js, web/frontend/src/components/RunConfiguration/Form/FormItems/LoadConfiguration/__snapshots__/LoadConfigurationFormItem.test.js.snap, web/frontend/src/components/RunConfiguration/Form/RunConfigurationForm.js, web/frontend/src/lib/api/__tests__/runConfiguration.test.js, web/frontend/src/lib/api/endpoints/runConfiguration.js, web/frontend/src/pages/TestsSingle.js
A toggle button has been added to Load Profiler in Test Configuration, allowing for Load Profiler to be enable or disabled.
Closes #146
=> feat: toggle enable/disable load profiler, tests added

agent/maestro_agent/libs/threading.py, agent/maestro_agent/services/jmeter/properties.py, agent/tests/services/jmeter/test_properties.py
Fix the sending of the parameter load_profile without spaces and the starts RPS should never be lower than 1.
Closes #719
=> fix: Change the load_profile pattern sent to Jmeter container

web/api/maestro_api/swagger/template.yml, web/api/maestro_api/validation_schemas.py, web/frontend/src/components/Dashboard/RunsMonitor/RunsMonitor.js, web/frontend/src/context/Running/RunningContext.js, web/frontend/src/lib/api/endpoints/run.js
Previously, all runs were fetched from backedn and then filtered on the frontend to display on Dashboard just the ones with the statuses "CREATING", "PENDING" and "RUNNING".
Now, this logic is all done in the backend and just one call is make to retrieve all the runs that contain this status.
Also, the update interval of this call was increased to 15s.
Closes #721
=> Fix: Changes runs filtering logic to backend, increases update interval to 15s

web/frontend/src/components/Run/RunningStatus/AnalyticCharts/HitsErrorsLine/HitsErrorsLine.js, web/frontend/src/components/Run/RunningStatus/AnalyticCharts/ResponseCodesLine/ResponseCodesLine.js, web/frontend/src/components/Run/RunningStatus/AnalyticCharts/ResponseTimeLine/ResponseTimeLine.js, web/frontend/src/components/Run/RunningStatus/AnalyticCharts/RunAnalyticCharts.js
The beginning of the Load profiler chart, (the "Expected Hits" line), is now synced with the first metrics received, meaning they both start at the same time.
Closes #736
=> Fix: Load Profiler not synced with metrics

web/api/maestro_api/scheduler.py, web/api/tests/test_scheduler.py
Agents with DISABLED status are no longer updated to UNAVAILABLE after 60 seconds
Closes #786
=> Fix: Disabled agents show as UNAVAILABLE after 60 seconds

web/api/maestro_api/controllers/run.py, web/api/tests/routes/test_run.py
Search bar in the _History_ tab is now case insensitive.
Closes #792
=> Fix: Search bar in History tab is case sensitive

web/frontend/src/components/Run/RunningStatus/EndpointCharts/RunEndpointCharts.js
When a prefix is applied to be excluded from the _Endpoints_ chart, it will appear as a tag. The use can now know how many and which prefixes are currently being applied to the chart.
Closes #750
=> Feat: Excluded prefixes being applied are shown as tags

web/frontend/src/components/Run/RunningStatus/AnalyticCharts/HitsErrorsLine/HitsErrorsLine.js
If a Load Profiler was enabled but was empty and a custom property "load_profile" was given, the chart would not render and thrown an error since the Load Profiler would overrule the custom property but it was empty.
Closes #806
=> Fix: Chart not appearing in Overview tab when opening a run from History

agent/maestro_agent/services/jmeter/properties.py, agent/tests/services/jmeter/test_properties.py, web/frontend/src/components/Run/RunningStatus/AnalyticCharts/HitsErrorsLine/HitsErrorsLine.js, web/frontend/src/components/Run/RunningStatus/AnalyticCharts/RunAnalyticCharts.js, web/frontend/src/components/RunConfiguration/Form/FormItems/LoadConfiguration/LoadConfigurationChart/LoadConfigurationChart.js, web/frontend/src/lib/charts/datasets/__tests__/loadProfileToTimeframe.test.js, web/frontend/src/lib/charts/datasets/loadProfileToTimeframe.js
The chart drawn in the Load Profiler component when creating a test is representative of the RPS values of 1 agent. The chart drawn when the test is executed is representative of the expected RPS of all agents combined.
Load Profiler in a Run Configuration (Values for 1 agent):
Load Profiler during a Run (with 2 agents):
Closes #765
=> Fix: Load Profile values are divided among agents

web/frontend/src/components/Run/RunningStatus/AnalyticCharts/RunAnalyticCharts.js, web/frontend/src/components/Run/StatusMonitor/RunStatusMonitor.js
Runs that were in _History_, i.e. that had Ended, Finished, or got an Error during their execution, no longer make API calls to update the Run data or to auto refresh their metrics.
Closes #807
=> Fix: High number of API calls in ended runs from history

web/api/maestro_api/controllers/run_metric.py, web/api/tests/routes/test_run_metric.py
The metrics from a Run are now downloaded as a zip file. The zip content will be the same .csv file that was previously downloaded.
Closes #788
=> Feat: Run metrics are now downloaded as zip

agent/maestro_agent/app_state.py
When an Agent is initialized, several additional pieces of information will be displayed in its log beside the previous id, hostname, and IP.
Closes #819
=> Feat: Agents variables values are now displayed in log when the Agent is initiated

web/api/maestro_api/controllers/run_metric.py
Previously, a zip file had the same size as the csv in it, which is not expected. Now, the zip file is much smaller than the csv inside it, which shows the compression is now being applied.
Closes #828
=> Fix: Zip files are not compressed
